title: The January Journal
description: Essays and dissections
theme: jekyll-theme-minimal  # optional, but we'll use custom CSS anyway
baseurl: "" 
url: "https://klkbertiga.github.io"   # your GitHub Pages domain
